// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3o6VQTVyg5p3A4wtJ1j-b2huTUkY9Iv0',
    appId: '1:44114243423:web:8d99e53039ffd0f81a90ea',
    messagingSenderId: '44114243423',
    projectId: 'simpleecommerce-9d07e',
    authDomain: 'simpleecommerce-9d07e.firebaseapp.com',
    storageBucket: 'simpleecommerce-9d07e.appspot.com',
    measurementId: 'G-XVM8DB06EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTU2NH7KPPGNp_pY0mIugHC28kT7Q35bY',
    appId: '1:44114243423:android:4b1d99315e14d4b11a90ea',
    messagingSenderId: '44114243423',
    projectId: 'simpleecommerce-9d07e',
    storageBucket: 'simpleecommerce-9d07e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmllfknCRQBpDRX_vjKzyXlLK9G8ER9-I',
    appId: '1:44114243423:ios:a0193b44e213a5201a90ea',
    messagingSenderId: '44114243423',
    projectId: 'simpleecommerce-9d07e',
    storageBucket: 'simpleecommerce-9d07e.appspot.com',
    iosBundleId: 'com.example.simpleEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmllfknCRQBpDRX_vjKzyXlLK9G8ER9-I',
    appId: '1:44114243423:ios:a0193b44e213a5201a90ea',
    messagingSenderId: '44114243423',
    projectId: 'simpleecommerce-9d07e',
    storageBucket: 'simpleecommerce-9d07e.appspot.com',
    iosBundleId: 'com.example.simpleEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3o6VQTVyg5p3A4wtJ1j-b2huTUkY9Iv0',
    appId: '1:44114243423:web:8cc320288df587211a90ea',
    messagingSenderId: '44114243423',
    projectId: 'simpleecommerce-9d07e',
    authDomain: 'simpleecommerce-9d07e.firebaseapp.com',
    storageBucket: 'simpleecommerce-9d07e.appspot.com',
    measurementId: 'G-NFF010J7WZ',
  );
}
